# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brad Knowles
description: The technology blog of Brad Knowles, Senior Solutions Developer with Leading EDJE in Columbus, Ohio.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
url: "http://bradknowles.com"
twitter_username: Brad_Knowles
github_username:  BradKnowles

# Build settings
markdown: kramdown

# Include directory for non-post pages.
include: ['_pages']
